Resources:
  MerchantsWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: writeHandler.handler
      Runtime: nodejs14.x
      Tracing: Active
      MemorySize: 1024
      ReservedConcurrentExecutions: 20
      Environment:
        Variables:
          ENDPOINT: !Ref endpoint
          DB_TABLE_NAME: !Ref MerchantsTableName
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: !Ref LogLevel
          AWSREGION: !Ref AWS::Region
