name: ECRPush

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  get-variables:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      git_commit_short: ${{ steps.get_hash.outputs.git_commit_short }}
      project_name: ${{ steps.get_project.outputs.project_name }}
      dependabot_project: ${{ steps.get_dependabot.outputs.dependabot_project }}
      image_name: ${{ steps.get_image.outputs.image_name }}
    steps:
      - uses: actions/checkout@v3
      - id: get_hash
        run: echo "git_commit_short=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT
      - id: get_project
        run: echo "project_name=`echo ${GITHUB_REPOSITORY} | cut -c 10-`" >> $GITHUB_OUTPUT
      - id: get_dependabot
        run: echo "dependabot_project=`echo ${GITHUB_REPOSITORY} | cut -c 10-`" >> $GITHUB_OUTPUT
      - id: get_image
        run: echo "image_name=`echo Docker/Image/Name`" >> $GITHUB_OUTPUT
  show_variables:
    runs-on: ubuntu-latest
    needs: get-variables
    steps:
      - run: echo ${{needs.get-variables.outputs.git_commit_short}}
      - run: echo ${{needs.get-variables.outputs.project_name}} 
      - run: echo ${{needs.get-variables.outputs.dependabot_project}}
      - run: echo ${{needs.get-variables.outputs.image_name}}
  integracion-cd:
    runs-on: ubuntu-latest
    needs: [get-variables]
    steps:
      - run: echo ${{needs.get-variables.outputs.image_name}} | tr xyz -



                        
