name: Get Variables

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  get-variables:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      GIT_COMMIT_SHORT: ${{ steps.get_hash.outputs.git_commit_short }}
      PROJECT_NAME: ${{ steps.get_project.outputs.project_name }}
      DEPENDABOT_PROJECT: ${{ steps.get_dependabot.outputs.dependabot_project }}
      LAMBDA_NAME: ${{ steps.get_image.outputs.LAMBDA_NAME }}
      GIT_BRANCH_STANDARD: ${{ steps.get_branch_standard.outputs.GIT_BRANCH_STANDARD }}
      TEMPLATE_FILE: ${{ steps.get_template_file.outputs.TEMPLATE_FILE }}
      TEAM_NAME: ${{ steps.get_team_name.outputs.TEAM_NAME }}
      ISITNODE: ${{ steps.get_is_node.outputs.ISITNODE}}
      TEST: ${{ steps.this_is_a_test.outputs.TEST}}
    steps:
      - uses: actions/checkout@v3
      - id: get_hash
        run: echo "GIT_COMMIT_SHORT=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT
      - id: get_project
        run: echo "PROJECT_NAME=`echo ${GITHUB_REPOSITORY} | cut -c 10-`" >> $GITHUB_OUTPUT
      - id: get_dependabot
        run: echo "DEPENDABOT_PROJECT=`echo ${GITHUB_REPOSITORY} | cut -c 10-`" >> $GITHUB_OUTPUT
      - id: get_image
        run: echo "LAMBDA_NAME=`printf $(grep LAMBDA_NAME deployment.env | xargs)`" >> $GITHUB_OUTPUT
      - id: get_branch_standard
        run: echo "GIT_BRANCH_STANDARD=`echo ${GITHUB_REF#refs/heads/} | tr / -`" >> $GITHUB_OUTPUT
      - id: get_template_file
        run: echo "TEMPLATE_FILE=`$(echo find . -maxdepth 1 -name template.y*)`" >> $GITHUB_OUTPUT
      - id: get_team_name
        run: echo "TEAM_NAME=`printf $(grep TEAM_NAME deployment.env | xargs)`" >> $GITHUB_OUTPUT
      - id: this_is_a_test
        run: echo "TEST= ${{ secrets.TEST }}"
      - id: get_is_node
        run: |
         (grep nodejs template.y* >> result.txt) || (touch result.txt)
          if [ -s result.txt ];
          then
            echo "ISITNODE=TRUE" >> $GITHUB_OUTPUT
          else
            echo "ISITNODE=FALSE" >> $GITHUB_OUTPUT
          fi
      
  show_variables:
    runs-on: ubuntu-latest
    needs: get-variables
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{needs.get-variables.outputs.GIT_COMMIT_SHORT}}
      - run: echo ${{needs.get-variables.outputs.TEST}}
      - run: |
          COUNT_SERVERLESS_WORD=`grep -o -i AWS::Serverless::Function template.y* | wc -l`
          COUNT_CONCURRENCY_WORD=`grep -o -i ReservedConcurrentExecutions template.y* | wc -l`
          if [ $COUNT_CONCURRENCY_WORD -ge $COUNT_SERVERLESS_WORD ];
          then
            echo "ReservedConcurrentExecutions Lambda parameter configured"
          else
            echo "::error ::ERROR: ReservedConcurrentExecutions Lambda parameter not configured" && exit 1
          fi
            
#  integration-cd:
#    runs-on: ubuntu-latest
#    needs: [get-variables]
#    steps:
#      - name: Deploy fase
#        run: aws --region us-west-2 lambda invoke --function-name dev-ecs-feature-branch-temp --payload '{ "project":"${{needs.get-variables.outputs.project_name}} ", "branch":"${{needs.get-variables.outputs.GIT_BRANCH_STANDARD}}", "commit":"${{needs.get-variables.outputs.git_commit_short}}"}' responde.json


