# This is a basic workflow to help you get started with Actions

name: variables

# Controls when the workflow will run
on:
  workflow_call:
    outputs:
      git_commit_short:
        description: 'short commit hash'
        value: ${{ jobs.get-env.outputs.git_commit_short }}
      project_name:
        description: 'Repository name'
        value: ${{ jobs.get-env.outputs.project_name }}
      dependabot_project:
        description: 'Repository name'
        value: ${{ jobs.get-env.outputs.dependabot_project }}
      image_name:
        description: 'Docker image name'
        value: ${{ jobs.get-env.outputs.image_name }}
jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
      - name: calcular hash
        id: get_hash
        run: echo "::set-output name=git_commit_short::`echo ${GITHUB_SHA} | cut -c1-8`"
      - name: Obtener nombre del proyecto
        id: get_project
        run: echo "::set-output name=project_name::`echo ${github_repository} | cut -c 10-`"
      - name: Obtener nombre del proyecto
        id: get_dependabot
        run: echo "::set-output name=dependabot_project::`echo ${github_repository} | cut -c 10-`"
      - name: Obtener nombre del proyecto
        id: get_image
        run: echo "::set-output name=image_name::`cat DockerImageName`"

    outputs:
      git_commit_short: ${{ steps.get_hash.outputs.git_commit_short }}
      project_name: ${{ steps.get_project.outputs.project_name }}
      dependabot_project: ${{ steps.get_dependabot.outputs.dependabot_project }}
      image_name: ${{ steps.get_image.outputs.image_name }}
      

      
      
